<template>
  <div class='page-container page-component'>
    <div class="el-col el-col-24 el-col-xs-24 el-col-sm-18"><section class="content"><h2 id="button-an-niu"><a href="http://element.eleme.io/#/zh-CN/component/button#button-an-niu" aria-hidden="true" class="header-anchor"></a> Button 按钮</h2><p>常用的操作按钮。</p><h3 id="ji-chu-yong-fa"><a href="http://element.eleme.io/#/zh-CN/component/button#ji-chu-yong-fa" aria-hidden="true" class="header-anchor"></a> 基础用法</h3><p>基础的按钮用法。</p><div class="demo-block demo-box demo-zh-CN demo-button"><div class="source"><button type="button" class="el-button el-button--default"><!----><!----><span>默认按钮</span></button><button type="button" class="el-button el-button--primary"><!----><!----><span>主要按钮</span></button><button type="button" class="el-button el-button--text"><!----><!----><span>文字按钮</span></button></div><div  class="meta" style="height: 127px;"><div class="description"><p>Button 组件默认提供7种主题，由<code>type</code>属性来定义，默认为<code>default</code>。</p><button type="button" class="el-button el-tooltip el-button--primary el-button--small"><!----><!----><span>在线运行</span></button></div><div class="highlight"><pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">el-button</span>&gt;</span>默认按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span>&gt;</span>主要按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"text"</span>&gt;</span>文字按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
</code></pre></div></div><div class="demo-block-control" v-meta  ><i class="el-icon-caret-top"></i><span style="display: none;" class="">隐藏代码</span></div></div><h3 id="jin-yong-zhuang-tai"><a href="http://element.eleme.io/#/zh-CN/component/button#jin-yong-zhuang-tai" aria-hidden="true" class="header-anchor"></a> 禁用状态</h3><p>按钮不可用状态。</p><div class="demo-block demo-box demo-zh-CN demo-button"><div class="source"><button disabled="disabled" type="button" class="el-button el-button--default is-disabled is-plain"><!----><!----><span>主要按钮</span></button><button disabled="disabled" type="button" class="el-button el-button--primary is-disabled"><!----><!----><span>主要按钮</span></button><button disabled="disabled" type="button" class="el-button el-button--text is-disabled"><!----><!----><span>文字按钮</span></button></div><div class="meta" style="height: 127px;"><div class="description"><p>你可以使用<code>disabled</code>属性来定义按钮是否可用，它接受一个<code>Boolean</code>值。</p><button type="button" class="el-button el-tooltip el-button--primary el-button--small"><!----><!----><span>在线运行</span></button></div><div class="highlight"><pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">:plain</span>=<span class="hljs-string">"true"</span> <span class="hljs-attr">:disabled</span>=<span class="hljs-string">"true"</span>&gt;</span>主要按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">:disabled</span>=<span class="hljs-string">"true"</span>&gt;</span>主要按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"text"</span> <span class="hljs-attr">:disabled</span>=<span class="hljs-string">"true"</span>&gt;</span>文字按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
</code></pre></div></div><div class="demo-block-control" v-meta ><i class="el-icon-caret-top"></i><span style="display: none;" class="">隐藏代码</span></div></div><h3 id="you-yan-se-qing-xiang"><a href="http://element.eleme.io/#/zh-CN/component/button#you-yan-se-qing-xiang" aria-hidden="true" class="header-anchor"></a> 有颜色倾向</h3><p>不同的颜色倾向代表不同的提示</p><div class="demo-block demo-box demo-zh-CN demo-button"><div class="source intro-block"><div class="block"><span class="demonstration">默认显示颜色</span><span class="wrapper"><button type="button" class="el-button el-button--success"><!----><!----><span>成功按钮</span></button><button type="button" class="el-button el-button--warning"><!----><!----><span>警告按钮</span></button><button type="button" class="el-button el-button--danger"><!----><!----><span>危险按钮</span></button><button type="button" class="el-button el-button--info"><!----><!----><span>信息按钮</span></button></span></div><div class="block"><span class="demonstration">hover 显示颜色</span><span class="wrapper"><button type="button" class="el-button el-button--success is-plain"><!----><!----><span>成功按钮</span></button><button type="button" class="el-button el-button--warning is-plain"><!----><!----><span>警告按钮</span></button><button type="button" class="el-button el-button--danger is-plain"><!----><!----><span>危险按钮</span></button><button type="button" class="el-button el-button--info is-plain"><!----><!----><span>信息按钮</span></button></span></div></div><div class="meta" style="height: 430px;"><div class="description"><p>朴素按钮同样设置了不同的<code>type</code>属性对应的样式（可选值同上），默认为<code>info</code>。设置<code>plain</code>属性，它接受一个<code>Boolean</code>。注意，在该情况下，<code>type</code>虽然可以为<code>text</code>，但是是没有意义的，会显示为<code>text button</code>的样式。</p><button type="button" class="el-button el-tooltip el-button--primary el-button--small"><!----><!----><span>在线运行</span></button></div><div class="highlight"><pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"block"</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"demonstration"</span>&gt;</span>默认显示颜色<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"wrapper"</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"success"</span>&gt;</span>成功按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"warning"</span>&gt;</span>警告按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"danger"</span>&gt;</span>危险按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"info"</span>&gt;</span>信息按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
  <span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">div</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"block"</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"demonstration"</span>&gt;</span>hover 显示颜色<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"wrapper"</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">:plain</span>=<span class="hljs-string">"true"</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"success"</span>&gt;</span>成功按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">:plain</span>=<span class="hljs-string">"true"</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"warning"</span>&gt;</span>警告按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">:plain</span>=<span class="hljs-string">"true"</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"danger"</span>&gt;</span>危险按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">:plain</span>=<span class="hljs-string">"true"</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"info"</span>&gt;</span>信息按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
  <span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">div</span>&gt;</span>
</code></pre></div></div><div class="demo-block-control" v-meta ><i class="el-icon-caret-top"></i><span style="display: none;" class="">隐藏代码</span></div></div><h3 id="tu-biao-an-niu"><a href="http://element.eleme.io/#/zh-CN/component/button#tu-biao-an-niu" aria-hidden="true" class="header-anchor"></a> 图标按钮</h3><p>带图标的按钮可增强辨识度(有文字)或节省空间(无文字)。</p><div class="demo-block demo-box demo-zh-CN demo-button"><div class="source"><button type="button" class="el-button el-button--primary"><!----><i class="el-icon-edit"></i><!----></button><button type="button" class="el-button el-button--primary"><!----><i class="el-icon-share"></i><!----></button><button type="button" class="el-button el-button--primary"><!----><i class="el-icon-delete"></i><!----></button><button type="button" class="el-button el-button--primary"><!----><i class="el-icon-search"></i><span>搜索</span></button><button type="button" class="el-button el-button--primary"><!----><!----><span>上传<i class="el-icon-upload el-icon--right"></i></span></button></div><div class="meta" style="height: 177px;"><div class="description"><p>设置<code>icon</code>属性即可，icon 的列表可以参考 Element 的 icon 组件，也可以设置在文字右边的 icon ，只要使用<code>i</code>标签即可，可以使用自定义图标。</p><button type="button" class="el-button el-tooltip el-button--primary el-button--small"><!----><!----><span>在线运行</span></button></div><div class="highlight"><pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">"edit"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">"share"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">"delete"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">"search"</span>&gt;</span>搜索<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span>&gt;</span>上传<span class="hljs-tag">&lt;<span class="hljs-name">i</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"el-icon-upload el-icon--right"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">i</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
</code></pre></div></div><div class="demo-block-control" v-meta ><i class="el-icon-caret-top"></i><span style="display: none;" class="">隐藏代码</span></div></div><h3 id="an-niu-zu"><a href="http://element.eleme.io/#/zh-CN/component/button#an-niu-zu" aria-hidden="true" class="header-anchor"></a> 按钮组</h3><p>以按钮组的方式出现，常用于多项类似操作。</p><div class="demo-block demo-box demo-zh-CN demo-button"><div class="source"><div class="el-button-group"><button type="button" class="el-button el-button--primary"><!----><i class="el-icon-arrow-left"></i><span>上一页</span></button><button type="button" class="el-button el-button--primary"><!----><!----><span>下一页<i class="el-icon-arrow-right el-icon--right"></i></span></button></div><div class="el-button-group"><button type="button" class="el-button el-button--primary"><!----><i class="el-icon-edit"></i><!----></button><button type="button" class="el-button el-button--primary"><!----><i class="el-icon-share"></i><!----></button><button type="button" class="el-button el-button--primary"><!----><i class="el-icon-delete"></i><!----></button></div></div><div class="meta" style="height: 241px;"><div class="description"><p>使用<code>&lt;el-button-group&gt;</code>标签来嵌套你的按钮。</p><button type="button" class="el-button el-tooltip el-button--primary el-button--small"><!----><!----><span>在线运行</span></button></div><div class="highlight"><pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">el-button-group</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">"arrow-left"</span>&gt;</span>上一页<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span>&gt;</span>下一页<span class="hljs-tag">&lt;<span class="hljs-name">i</span> <span class="hljs-attr">class</span>=<span class="hljs-string">"el-icon-arrow-right el-icon--right"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">i</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">el-button-group</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button-group</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">"edit"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">"share"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">icon</span>=<span class="hljs-string">"delete"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">el-button-group</span>&gt;</span>
</code></pre></div></div><div class="demo-block-control" v-meta ><i class="el-icon-caret-top"></i><span style="display: none;" class="text-slide-enter-to">隐藏代码</span></div></div><h3 id="jia-zai-zhong"><a href="http://element.eleme.io/#/zh-CN/component/button#jia-zai-zhong" aria-hidden="true" class="header-anchor"></a> 加载中</h3><p>点击按钮后进行数据加载操作，在按钮上显示加载状态。</p><div class="demo-block demo-box demo-zh-CN demo-button"><div class="source"><button type="button" class="el-button el-button--primary is-loading"><i class="el-icon-loading"></i><!----><span>加载中</span></button></div><div class="meta" style="height: 127px;"><div class="description"><p>要设置为 loading 状态，只要设置<code>loading</code>属性为<code>true</code>即可。</p><button type="button" class="el-button el-tooltip el-button--primary el-button--small"><!----><!----><span>在线运行</span></button></div><div class="highlight"><pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">:loading</span>=<span class="hljs-string">"true"</span>&gt;</span>加载中<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
</code></pre></div></div><div class="demo-block-control" v-meta ><i class="el-icon-caret-top"></i><span style="display: none;" class="text-slide-enter-to">隐藏代码</span></div></div><h3 id="bu-tong-chi-cun"><a href="http://element.eleme.io/#/zh-CN/component/button#bu-tong-chi-cun" aria-hidden="true" class="header-anchor"></a> 不同尺寸</h3><p>Button 组件提供除了默认值以外的三种尺寸，可以在不同场景下选择合适的按钮尺寸。</p><div class="demo-block demo-box demo-zh-CN demo-button"><div class="source"><button type="button" class="el-button el-button--primary el-button--large"><!----><!----><span>大型按钮</span></button><button type="button" class="el-button el-button--primary"><!----><!----><span>正常按钮</span></button><button type="button" class="el-button el-button--primary el-button--small"><!----><!----><span>小型按钮</span></button><button type="button" class="el-button el-button--primary el-button--mini"><!----><!----><span>超小按钮</span></button></div><div class="meta" style="height: 127px;"><div class="description"><p>额外的尺寸：<code>large</code>、<code>small</code>、<code>mini</code>，通过设置<code>size</code>属性来配置它们。</p><button type="button" class="el-button el-tooltip el-button--primary el-button--small"><!----><!----><span>在线运行</span></button></div><div class="highlight"><pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">size</span>=<span class="hljs-string">"large"</span>&gt;</span>大型按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span>&gt;</span>正常按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">size</span>=<span class="hljs-string">"small"</span>&gt;</span>小型按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">el-button</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"primary"</span> <span class="hljs-attr">size</span>=<span class="hljs-string">"mini"</span>&gt;</span>超小按钮<span class="hljs-tag">&lt;/<span class="hljs-name">el-button</span>&gt;</span>
</code></pre></div></div><div class="demo-block-control" v-meta ><i class="el-icon-caret-top"></i>
<span style="display: none;" class="">隐藏代码</span></div></div><h3 id="attributes">
  <a href="http://element.eleme.io/#/zh-CN/component/button#attributes" aria-hidden="true" class="header-anchor"></a> Attributes</h3><table class="table"><thead><tr><th>参数</th><th>说明</th><th>类型</th><th>可选值</th><th>默认值</th></tr></thead><tbody><tr><td>size</td><td>尺寸</td><td>string</td><td>large,small,mini</td><td>—</td></tr><tr><td>type</td><td>类型</td><td>string</td><td>primary,success,warning,danger,info,text</td><td>—</td></tr><tr><td>plain</td><td>是否朴素按钮</td><td>Boolean</td><td>—</td><td>false</td></tr><tr><td>loading</td><td>是否加载中状态</td><td>Boolean</td><td>—</td><td>false</td></tr><tr><td>disabled</td><td>是否禁用状态</td><td>boolean</td><td>—</td><td>false</td></tr><tr><td>icon</td><td>图标，已有的图标库中的图标名</td><td>string</td><td>—</td><td>—</td></tr><tr><td>autofocus</td><td>是否默认聚焦</td><td>boolean</td><td>—</td><td>false</td></tr><tr><td>native-type</td><td>原生 type 属性</td><td>string</td><td>button,submit,reset</td><td>button</td></tr></tbody></table></section>
  </div>
  </div>
</template>

<script>

export default {
  data () {
    return {
    }
  }
};
</script>